### ISSUE TITLE
Error message on PMML creation

### ISSUE THREAD

**Issue by jtenini** [jpmml/jpmml-xgboost#1]
I've successfully created PMML for a classification model, but for a regression model, I'm getting the following error:

Exception in thread "main" java.io.IOException
    at org.jpmml.xgboost.XGBoostDataInput.readReserved(XGBoostDataInput.java:68)
    at org.jpmml.xgboost.Learner.load(Learner.java:52)
    at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:34)
    at org.jpmml.xgboost.Main.run(Main.java:92)
    at org.jpmml.xgboost.Main.main(Main.java:85)

**Comment by vruusmann** [comment]
What is your XGBoost version? Is it something different than `0.4.3`?

The method `XGBoostDataInput#readReserved(int)` expects to read an array of integer values, whereas every array element is expected to be `0`. If this expectation fails, then the above `java.io.IOException` is thrown.

The JPMML-XGBoost project includes a classification model `src/test/resources/xgboost/LogisticRegressionAudit.model`. Can you convert that one?

**Comment by jtenini** [comment]
I'm indeed using 0.4.3, but I'm not sure how to convert the LogisticRegressionAudit.model file without an accompanying fmap file.

**Comment by vruusmann** [comment]
All the accompanying `.fmap` files are located in the `src/test/resources/csv/` directory.

I suspect that your model file contains an extra four-byte header, which shifts all the remaining data to wrong positions. What are the first four bytes of your file? Does the converter succeed, if you delete/skip these four leading bytes? You could insert an extra `input.readInt()` to the beginning of the `Learner#load(...)` method.

By any chance, can you share the first 200 bytes of your model file (if not the entire file)?

**Comment by vruusmann** [comment]
In this case, you should match `LogisticRegressionAudit.model` with `Audit.fmap`.

**Comment by jtenini** [comment]
Thank you for the many helpful comments, it is now working. Congratulations on the very nice work on this project.

**Comment by vruusmann** [comment]
Not so quick! What was the winning solution - skipping the first four bytes? If so, then what were their values?

The JPMML-XGBoost knows about the "binf" header (eg. see the method `XGBoostDataInputStream#init(PushbackInputStream)`), but is there something else that should be recognized?

**Comment by jtenini** [comment]
I think this can be attributed to general user error. I didn't remove any characters, but rather reconstructed all files in question again. I think the most likely cause for error was that I was pointing to the result of the xgb.dump command instead of the xgb.save command for the .model file.
