### ISSUE TITLE
Clarification on missing value handling

### ISSUE THREAD

**Issue by travisbrady** [jpmml/jpmml-xgboost#11]
Hi, Thanks very much for jpmml-xgboost.

I'm using Python 3.5 and xgboost 0.6 and want to understand how to make the PMML missing value behavior match the xgb/Python behavior.

By default Python xgboost treats `numpy.nan` as missing. If I accept this default and dump my model (using `converter-executable-1.2-SNAPSHOT.jar`) to be used in a Java application how do I then express missing values at prediction time?  Java's `null`? Just omit them from the call?

Will everything "just work" as is?  Should I recode to some other missing identifier? 

I also noticed in RegTree.java (https://github.com/jpmml/jpmml-xgboost/blob/300f089aa4c55e2dd8b55ff93a8ceb1d0f278a57/src/main/java/org/jpmml/xgboost/RegTree.java#L98) that the missingValueStrategy is hardcoded to `defaultChild`. Is that the PMML equivalent of the standard xgboost behavior?

thanks very much.

**Comment by vruusmann** [comment]
> In a Java application how do I then express missing values at prediction time? Java's null? Just omit them from the call?

Depends on your Java PMML engine. If you're using the JPMML-Evaluator library, then you can obtain a "missing value" `org.jpmml.evaluator.FieldValue` instance by invoking an appropriate `org.jpmml.evaluator.InputField#prepare(Object)` with the `null` value:
```
InputField inputField = ...;
FieldValue missingValue = inputField.prepare(null);
```

Here, the value of `missingValue` variable will also be a `null` value. My advice is that you should never implement any `missingValue == null`-type checks and logic in your application code. Simply carry this `null` value over to the arguments map.

Of course, it may happen that someone has modified the "raw" XGBoost PMML document by specifying a custom missing value handling policy (eg. by setting the value of `MiningField@missingValueReplacement` attribute).

Starting from JPMML-XGBoost version 1.1.4 it's possible to define which valid value(s) should be interpreted as missing values: https://github.com/jpmml/jpmml-xgboost/commit/6850d873b833eb01edf13269fd15fe1578477e37

For example, if your dataset encodes missing values as `-999`, then you can easily "enhance" the PMML document with appropriate markup by invoking the JPMML-XGBoost command-line application with the `--missing-value` option. IIRC, similar functionality should be available also in [r2pmml](https://github.com/jpmml/r2pmml) and [sklearn2pmml](https://github.com/jpmml/sklearn2pmml) packages. You might want to check them out, as they're generally easier to work with than the JPMML-XGBoost command-line application.

> The missingValueStrategy is hardcoded to `defaultChild`. Is that the PMML equivalent of the standard xgboost behavior?

The XGBoost behaviour is to send missing values to "majority's direction". PMML does not have the concept of a "majority direction" (although something custom could be implemented around the `Node@recordCount` attribute), so you need to point directly to some child `Node` element.
