### ISSUE TITLE
Version of created PMML

### ISSUE THREAD

**Issue by Ginliebhaber** [jpmml/jpmml-xgboost#12]
Hello,
is it possible to specify the version of the created PMML?

Thanks in advance.

**Comment by vruusmann** [comment]
The JPMML-XGBooost library only creates PMML schema version 4.3 documents, as it allows for more compact representation of decision tree ensembles than older PMML schema versions.

For example: http://mantis.dmg.org/view.php?id=149

**Comment by Ginliebhaber** [comment]
Thank you very much for your fast answer. 
Is there a Java approach to transform PMML 4.3 to 4.2 ?
Unfortunately we need PMML v4.2.

Thank you very much in advance.
