### ISSUE TITLE
Clarification on behavior with respect to missing features

### ISSUE THREAD

**Issue by travisbrady** [jpmml/jpmml-xgboost#13]
How does this library and jpmml-evaluator deal with missing features?
For example, xgboost and lightgbm's Python bindings allow for missing values with nan by default. 

When scoring with a model trained with these bindings using nan as the missing value indicator, how should one handle missing features in Java? Not set them at all? Or do we need to specify something other than nan as the missing value and then use that on the java side?

thanks

**Comment by vruusmann** [comment]
JPMML-XGBoost is an open source software. By grepping the codebase for relevant keywords (in this case "missing"), it should be possible to find the answer yourself:
https://github.com/jpmml/jpmml-xgboost/blob/master/src/main/java/org/jpmml/xgboost/Main.java#L58-L62
