### ISSUE TITLE
Error on PMML creation when setting eval_metric

### ISSUE THREAD

**Issue by svijaysc** [jpmml/jpmml-xgboost#14]
Hi, 

I am using the python xgboost API and get the following error during PMML creation ONLY when I set eval_metric in the Booster parameters : 
```
Exception in thread "main" java.io.IOException
	at org.jpmml.xgboost.XGBoostDataInput.readReserved(XGBoostDataInput.java:82)
	at org.jpmml.xgboost.Learner.load(Learner.java:65)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:34)
	at org.jpmml.xgboost.Main.run(Main.java:117)
	at org.jpmml.xgboost.Main.main(Main.java:110)
```
Using the latest release of both jpmml-xgboost and xgboost. Would appreciate any insight/fixes.

**Comment by vruusmann** [comment]
Must be the case that if the `eval_metric` parameter is set, then there's something written into the "reserved area" of XGBoost data structure.

JPMML-XGBoost expects the "reserved area" to be filled with zero bytes. Any non-zero byte is treated as an error condition.

As a workaround, don't use the `eval_metric` parameter during training, or try to nullify/zero out that part of the XGBoost data structure before dumping it into file.

Alternatively, you might customize the JPMML-XGBoost library not to check the value of "reserved area" bytes. You could start by simply commenting out this line:
https://github.com/jpmml/jpmml-xgboost/blob/master/src/main/java/org/jpmml/xgboost/XGBoostDataInput.java#L82

**Comment by svijaysc** [comment]
Thanks for getting back to me so quickly!

To your point, when I train on a datalab instance or just locally this does not happen, even if eval_metric is set. This seems to happen only when I train on my GCE instance. All libraries are the exact same version everywhere. 

To your first point, I am temporarily training without setting eval_metric, but this is an important requirement for my use-case and would like to use it.

To your second point, how do I zero out that portion of the data structure before writing it out?

Commenting out those lines still give me errors in other places!
Thank you for your help.

**Comment by vruusmann** [comment]
> All libraries are the exact same version everywhere.

Hope you're using the latest versions, because I'd hate to waste time on troubleshooting legacy versions.

The libraries might be the same, but the library itself might contain platform-specific logic. In other words, the library performs extra work on GCE platform, and stores those results in the "reserved area".

> Commenting out those lines still give me errors in other places!

Keep commenting out those other places as well.

For example, it's OK (at least temporarily) to leave some some input unconsumed:
https://github.com/jpmml/jpmml-xgboost/blob/master/src/main/java/org/jpmml/xgboost/XGBoostUtil.java#L64
