### ISSUE TITLE
JPMML v1.2.1  produces a PMML file that is not 4.3 compliant: attribute 'x-mathContext'

### ISSUE THREAD

**Issue by CamCairns** [jpmml/jpmml-xgboost#15]
I recently upgraded the version of jPMML I was using to the latest release (v1.2.1). The resulting PMML files produced now contains an attribute 'x-mathContext="float"' in the <TreeModel> and <MiningModel> elements. This is not compliant with the PMML 4.3 xsd schema. Is this intended behaviour?

**Comment by vruusmann** [comment]
> The resulting PMML files produced now contains an attribute 'x-mathContext="float"' in the and elements.

XGBoost defaults to 32-bit floating-point operations, whereas PMML defaults to 64-bit floating-point operations. If you want to be able to exactly reproduce XGBoost predictions in PMML, then you must inform the PMML engine that it needs to switch to 32-bit floating-point mode.

For more discussion, see here:
http://mantis.dmg.org/view.php?id=179

> This is not compliant with the PMML 4.3 xsd schema.

The PMML specification permits vendor extension elements and attributes. They are distinguished from standard elements by the "X-" and "x-" prefix to their names (see the "Extension mechanism" section):
http://dmg.org/pmml/v4-3/GeneralStructure.html

Hopefully, the next version of the PMML specification will make the `mathContext` attribute official, and it will be possible to drop the "x-" prefix from its name.

> Is this intended behaviour?

This is the intended and correct behaviour.

If you don't like extension elements and attributes, then you can get rid of them by applying a simple XML filter to your PMML documents.

**Comment by CamCairns** [comment]
Great, thanks for that Villu
