### ISSUE TITLE
how do I represents missing value in genDMatrix function?

### ISSUE THREAD

**Issue by YshanChen** [jpmml/jpmml-xgboost#19]
Hi. We can use genDMatrix() to contruct xgb.DMatrix object from dense matrix and sparse matrix. In Package 'xgboost', there is a arguments 'missing' that is used to pick a float value that represents missing value in xgb.DMatrix function.
Just like `dtrain <- xgb.DMatrix(train$data, label=train$label, missing = -99)`,
but genDMatrix function don't have this arguments, how do I represents missing value in genDMatrix function when contruct xgb.DMatrix object? Thank you.

**Comment by vruusmann** [comment]
The function `r2pmml::genDMatrix()` operates on ordinary R `data.frame` objects. Data frame columns can be factors, numbers, booleans etc.

You would present a missing value as usual - it's a `NULL`.

For example, see my integration tests for the Audit dataset.  First, it is loaded from the CSV file as a "dense" `data.frame`:
https://github.com/jpmml/jpmml-xgboost/blob/master/src/test/R/xgboost.R#L173-L174

Then, it is converted to a "sparse" `data.frame` by replacing 25% of values with `NULL` values:
https://github.com/jpmml/jpmml-xgboost/blob/master/src/test/R/xgboost.R#L183
https://github.com/jpmml/jpmml-xgboost/blob/master/src/test/R/xgboost.R#L31-L40

The `r2pmml::genDMatrix()` functions works fine with both `data.frame` objects It will detect missing values using the `is.null()` function. It does not need any external help for that.

**Comment by YshanChen** [comment]
If I don't transform missing value to `NULL` in data, just use `-99` or `-1` to represent missing values, can `r2pmml::genDMatrix()`  distinguish that `-99` or `-1` represents missing value? Or must I present a missing value with `NULL`  when i use `r2pmml::genDMatrix()` ?  
Thanks very much .

**Comment by vruusmann** [comment]
If you're working in R environment then you should represent missing values using `NULL`. So, in your data frame, replace `-1` values with `NULL` values before invoking the `r2pmml::genDMatrix()` function, and everything will work as expected.

XGBoost does not have a special-purpose symbol for missing values, and therefore has to invent it's own "value masking" mechanism. The R way of doing things is much more intuitive.
