### ISSUE TITLE
Exception when running with JDK 9.0.4

### ISSUE THREAD

**Issue by sbrugman** [jpmml/jpmml-xgboost#24]
When running this application using the JDK 9.0.4, the following exception occurred:

`java.lang.NoClassDefFoundError: javax/activation....`

For me this problem was solved by following these instructions:
https://stackoverflow.com/a/48136912

**Comment by vruusmann** [comment]
This issue falls under this master issue: https://github.com/jpmml/jpmml-model/issues/17

I've introduced Java 9 compatibility into the JPMML-Model library (starting from the `1.4.1` version), but this updated library hasn't been propagated to the JPMML-Converter and JPMML-XGBoost libraries yet. Should happen in about two or three weeks' time.

**Comment by vruusmann** [comment]
Fixed in https://github.com/jpmml/jpmml-xgboost/commit/d05946c1b16b39b19b2f6881cad3df94e1d2ebc4
