### ISSUE TITLE
How to add recordCount and algorithm name to xgboost-pmml ?

### ISSUE THREAD

**Issue by USCYuandaDu** [jpmml/jpmml-xgboost#25]
Hi, the jpmml-xgboost is very useful in my project. Because I want to share my trained model.
The question is I do not know how to add recordCount into Tree Node attribute and I also want to add algorithm name.

Thank you!

Bests,
Yuanda

**Comment by vruusmann** [comment]
Was just blurting out my initial thoughts above.

As a solution, it should be possible to enable/disable the generation of `Node@recordCount` (and `Node@id`) attributes via conversion options.

Also, it would be trivial to set `MiningModel@algorithmName="XGBoost"`. But something also needs to be done at JPMML-R and JPMML-SkLearn library level to preserve the contents of the original `/PMML/Header/Application` element.

**Comment by USCYuandaDu** [comment]
Thank you for your reply. I got your point. And I was thinking can I add the attribute with using xml directly. Just a joke, haha.

**Comment by vruusmann** [comment]
> And I was thinking can I add the attribute with using xml directly.

Some Java programming will be definitely necessary.

However, if you have an existing PMML document (generated by whatever tree or tree ensemble learner algorithm), then it's possible to generate `Node@recordCount` programmatically for the dataset at hand.

Pseudo-code workflow:
```Java
org.jpmml.evaluator.Evaluator evaluator = ...
org.jpmml.evaluator.TargetField targetField = Iterables.getOnlyElement(evaluator.getTargetFields());

List<Map<FieldName, ?>> arguments = ...
for(Map<FieldName, ?> argument : arguments){
  Map<FieldName, ?> result = evaluator.evaluate(arguments);
  Object targetValue = result.get(targetField.getName());
  // Marker interface org.jpmml.evaluator.tree.HasDecisionPath was introduced in JPMML-Evaluator version 1.4.2
  if(targetValue instanceof HasDecisionPath){
    HasDecisionPath hasDecisionPath = (HasDecisionPath)targetValue;
    
    List<Node> pathNodes = hasDecisionPath.getDecisionPath();
    for(Node pathNode : pathNodes){
      // Increment record counts by one from the root node to the winning node
      node.setRecordCount(node.getRecordCount() + 1);
    }
  }
}
```

**Comment by USCYuandaDu** [comment]
Hi, vruusmann,
It's very kind of you to help me with the Psudo-code. It's really helpful. Since I was playing with xgboost. And in pmml, each tree was represented as <segment id=""> and each node was represented as <Node id="">. If I figure out the record count=100 of the node(id = 10)  which was in segment (id = 0). How can I set the recordCount to the Node so that the result line of that pmml could be <Node id="10" recordCount="100" score =".....">. And It is prefect if you could tell me the method with scala. 

Thank you!
Bests,
Yuanda

**Comment by vruusmann** [comment]
The above pseudo-code works with individual tree models (eg. DecisionTreeClassifier/DecisionTreeRegressor). There's no JPMML-Evaluator API yet for dealing with tree model ensembles (eg.  RandomForestClassifier/RandomForestRegressor and XGBoostClassifier/XGBoostRegressor). Maybe it will be possible to introduce a new interface `org.jpmml.evaluator.tree.HasDecisionPathEnsemble` or smth like that in the next JPMML-Evaluator version. Worth considering.

For getting record counts today, the simplest solution would be to modify the JPMML-XGBoost library as suggested in my first comment.

**Comment by USCYuandaDu** [comment]
Yeah, I got your point. But in your solution, for each tree, I should give the function maybe a map[Int, Int] which the key represent the node id and value represents the recordCount. So my question is that is the Node's id same between your code and xgboost?

**Comment by vruusmann** [comment]
> So my question is that is the Node's id same between your code and xgboost?

My code assigns assigns 1-based node indices, I have no idea if XGBoost uses the same indexing approach, or something else (eg. 0-based node indices):
https://github.com/jpmml/jpmml-xgboost/blob/master/src/main/java/org/jpmml/xgboost/RegTree.java#L106

However, please note that when the XGBoost model is compacted, then nodes are moved to different locations (eg. pulled up one or two levels), and their indices are set to null:
https://github.com/jpmml/jpmml-xgboost/blob/master/src/main/java/org/jpmml/xgboost/visitors/TreeModelCompactor.java#L118

Such XGBoost model compaction would also make the original record counts meaningless. So, if you want to have node identifiers and record counts, then you must first disable XGBoost model compaction:
https://github.com/jpmml/jpmml-xgboost/blob/master/src/main/java/org/jpmml/xgboost/Main.java#L89-L93

**Comment by USCYuandaDu** [comment]
Thank you for your fast reply. You answer was helpful and awesome. By looking through your code, I found that xgboost JPMML model got trained booster information with XGBoostDataInput. The idea was awesome and I was wonder how do you know the format of the Datainput. And It seems more nature to add recordCount into that datainput stream.

**Comment by USCYuandaDu** [comment]
I also wonder how could you match the feature schema? It seems complex.

**Comment by vruusmann** [comment]
> I also wonder if we could found recordCount in XGBoostDataInput?

I'm sorry to inform you that the binary XGBoost model object does not contain "record counts" information. Therefore, the only way to annotate the PMML data structure with this information (eg. setting the `Node@recordCount` attribute) appears to be programmatic, similar to what is proposed in https://github.com/jpmml/jpmml-xgboost/issues/25#issuecomment-400937506
