### ISSUE TITLE
Add `OPTION_MISSING_VALUE` conversion option

### ISSUE THREAD

**Issue by 52DL** [jpmml/jpmml-xgboost#28]
**Dear Ruusmann:**
        Recently, I train xgboost on spark with a very sparse dataset, I get weired result. Below is a clear example with one tree.
    **The dataset is like below:**
![image](https://user-images.githubusercontent.com/20773149/42487183-6d95066a-8432-11e8-945b-c8aec59f60dc.png)
    **The pipeline(a VectorAssembler follewed by a  XGBoostEstimator) trained transformed dataset:**
![image](https://user-images.githubusercontent.com/20773149/42487161-5711c888-8432-11e8-991e-3d1e3e96ab04.png)
     **The model trained:**
```
List(booster:[0]
0:[f0<2] yes=1,no=2,missing=2
	1:[f1<0.999999] yes=3,no=4,missing=4
		3:leaf=0.0701754
		4:leaf=0.21232
	2:leaf=-0
```
**The pmml generated:**
```
<Node id="1" defaultChild="3">
     <True/>
     <Node id="2" defaultChild="5">
	<SimplePredicate field="float(V1)" operator="lessThan" value="2.000001"/>
	     <Node id="4" score="0.07017544">
		<SimplePredicate field="float(V2)" operator="lessThan" value="0.999999"/>
	     </Node>
	     <Node id="5" score="0.21231979">
		<SimplePredicate field="float(V2)" operator="greaterOrEqual" value="0.999999"/>
	     </Node>
     </Node>
     <Node id="3" score="-0.0">
          <SimplePredicate field="float(V1)" operator="greaterOrEqual" value="2.000001"/>
     </Node>
</Node>
```

**1. XGBoost treat the many 0s in sparseVector as "missing" value in training and evaluating,
 so when  v1,v2,v3 all is zero,  xgboost get value in leaf=-0(probability=0.5).** 

**2. But Pmml will treat 0 as numeric "0",  
so when  v1,v2,v3 all is zero,  pmml get value in leaf=0.0701754(probability=0.517536).**

**Comment by vruusmann** [comment]
>  But Pmml will treat 0 as numeric "0"

You need to tell JPMML-XGBoost that `0` encodes a missing value:
https://github.com/jpmml/jpmml-xgboost/blob/master/src/main/java/org/jpmml/xgboost/Main.java#L60-L64

**Comment by 52DL** [comment]
I'm training xgboost on spark, and I used the method in [https://github.com/jpmml/jpmml-sparkml-xgboost](https://github.com/jpmml/jpmml-sparkml-xgboost)。
The Usage part uses `val pmmlBytes = ConverterUtil.toPMMLByteArray(df.schema, pipelineModel)`
Is there a way to pass the missing value to this method?

**Comment by vruusmann** [comment]
> The "Usage" part uses val pmmlBytes = ConverterUtil.toPMMLByteArray(df.schema, pipelineModel)

The `ConverterUtil#toPMMLByteArray(StructType, PipelineModel)` has been deprecated, and should not be used anymore:
http://openscoring.io/blog/2018/07/09/converting_sparkml_pipeline_pmml/

> Is there a way to pass the missing value to this method?

You could iterate over `DataDictionary/DataField` elements, and manually add `<Value value="0" property="missing"/>` child elements to each of them.

Otherwise, looks like this functionality should be implemented as JPMML-XGBoost conversion option, so that it could be handled uniformly across ML frameworks.

**Comment by 52DL** [comment]
Great job!  thanks a lot. 

> You could iterate over DataDictionary/DataField elements, and manually add <Value value="0" property="missing"/> child elements to each of them.

I'll give it a try.

**Comment by 52DL** [comment]
Dear vruusmann:
> You could iterate over DataDictionary/DataField elements, and manually add child elements to each of them.

This method worked. 
After i manually add `<Value value="0" property="missing"/>` child elements to each of related DataDictionary/DataField elements, the result from raw model **matched** that from pmml file.

**Comment by vruusmann** [comment]
```Java
PMML pmml = ...
Visitor visitor = new org.jpmml.model.visitors.AbstractVisitor(){

  @Override
  public VisitorAction visit(DataField dataField){
    dataField.addValues(new Value("0").setProperty(Value.Property.MISSING));

    return super.visit(dataField);
  }
};
visitor.applyTo(pmml);
```
