### ISSUE TITLE
question: which version of XGBoost are supported when using jpmml-xgboost version 1.3.2

### ISSUE THREAD

**Issue by Ying456123** [jpmml/jpmml-xgboost#30]
I'm using jpmml-xgboost version 1.3.2 with xgboost version 0.71, and find the supported objectives are not that enough in src/main/java/org/jpmml/xgboost/Learner.java. Is this because supportive version of xgboost is lower? Which version of xgboost is supported by jpmml-xgboost? I didn't find such information. Thanks a lot.

**Comment by vruusmann** [comment]
> Which version of xgboost is supported by jpmml-xgboost?

Any fairly recent version should be fine. IIRC, the first version of JPMML-XGBoost was published when XGBoost 0.4 was active.

**Comment by Ying456123** [comment]
Just want to confirm, so  jpmml-xgboost version 1.3.2 support xgboost version 0.71?  Thanks a lot.

**Comment by Ying456123** [comment]
@vruusmann

**Comment by vruusmann** [comment]
> jpmml-xgboost version 1.3.2 support xgboost version 0.71?

JPMML-XGBoost supports any XGBoost version in range from 0.4 to 0.71 (or whatever is the latest).
