### ISSUE TITLE
question: does this project support model saved at Big Endian machine

### ISSUE THREAD

**Issue by Ying456123** [jpmml/jpmml-xgboost#31]
I call booster.save_model method at Big Endian machine, and find the model cannot be transformed to the  pmml model. Does this project support model saved at Big Endian machine? Thanks a lot.

**Comment by Ying456123** [comment]
Hi,
Environment: IBM z/OS system
I attached two model files, booster_z.model is saved on IBM z/OS, and booster.model is saved on Mac OS. They have different byte order. From the jpmml-xgboost/src/main/org/jpmml/xgboost/XGBosotDataInput.java, I can see the code will new a DataInputStream to parse the model file, thus booster_z.model cannot be parsed correctly.  Besides, seems like the default  charset on z/OS system is "IBM1047", and new String(buffer) is ASCII, so the objective name cannot be recognized correctly. Do you have any advice?  I also attached the corresponding feature map file for your test convenience.
Thanks a lot.
Best Regards! Ying
[booster_z.tar.gz](https://github.com/jpmml/jpmml-xgboost/files/2286915/booster_z.tar.gz)
[booster.tar.gz](https://github.com/jpmml/jpmml-xgboost/files/2286916/booster.tar.gz)

**Comment by vruusmann** [comment]
@Ying456123 Thanks for the sample files.

The conversion of the `booster_z.model` sample file should now succeed if you specify `--byte-order` and `--charset` command-line options:
```
$ java -jar target/jpmml-xgboost-executable-1.3-SNAPSHOT.jar --model-input booster_z.model --fmap-input booster_z.fmap --byte-order BIG_ENDIAN --charset IBM1047 --pmml-output booster.pmml
```

**Comment by vruusmann** [comment]
@Ying456123 There's a chain of library releases (JPMML-Model -> JPMML-Converter -> JPMML-XGBoost -> JPMML-SkLearn -> SkLearn2PMML) that must take place before this functionality becomes available to end users.

Rough time estimate - two weeks from now.
