### ISSUE TITLE
'binary:hinge' are not supported

### ISSUE THREAD

**Issue by Ying456123** [jpmml/jpmml-xgboost#40]
@vruusmann 
I'm converting a xgboost model to a PMML model,  and find it is still not supported by jpmml-xgboost. Could you help to support it when you have time? Very appreciated.
The model:
```
import xgboost as xgb
import numpy as np
data = np.random.rand(5, 10)  # 5 entities, each contains 10 features
label = np.random.randint(2, size=5)  # binary target
dtrain = xgb.DMatrix(data, label=label)
param = {'max_depth': 2, 'eta': 1, 'silent': 1, 'objective': 'binary:hinge'}
plst = param.items()
model = xgb.train(plst, dtrain)
```

**Comment by tuanvayn** [comment]
did you resolve it? I've changed by adding objective case like below but more error thrown :(
![image](https://user-images.githubusercontent.com/22125166/70204671-fea25f80-1753-11ea-9274-e29321a4cbb8.png)

**Comment by tuanvayn** [comment]
Hi. Have someone solved?
