### ISSUE TITLE
xgboost pmml file output is null

### ISSUE THREAD

**Issue by kelierlawu** [jpmml/jpmml-xgboost#46]
Dear Villu,

@vruusmann 
I trained a xgboost classfier and successfully convrt it into a pmml model, however. when I ran an evaluator on it, it told me that the model's output is null. I checked the inside structure of that model and was able to find the output field,. How could it happen since there's no output of a model? 

Hope you can tell me! Thank you very much.

**Comment by vruusmann** [comment]
> it told me that the model's output is null. 

What really happened? Did the application throw some sort of exception, or did the evaluation complete normally with a `null` result?

A `null` result means "the prediction is a missing value". It's typical for decision tree ensembles (such as XGBoost) to yield a missing value when one or more input field values are missing ("missing values go in, missing values comes out").

A reproducible example would be appreciated.
