### ISSUE TITLE
Suppress/Discard no-op decision trees from the ensemble

### ISSUE THREAD

**Issue by kelierlawu** [jpmml/jpmml-xgboost#47]
@vruusmann 

Dear Villu,

I'm trying to load my pmml model while some exceptions occured, it said that my model is lacked of miningField. However, it's  a xgboost model and it looks fine on its structure to me. I can even run it to evalute a predition in my own demo. 

Could you please tell me how to solve this? I really need your help, looking forward to your reply.
Thanks.

**Comment by vruusmann** [comment]
> my boosting model has 500 trees, and over half of them actually serve no classification use.

Now I understand your issue - the XGBoost library is generating "dummy" decision trees in some cases.

The JPMML-XGBoost library should detect such markup, and try to simplify these. Here, it should suppress the generation of decision trees that 1) don't contain any useful splits, and 2) are making a zero contribution (`Node@score=0`) to the GBDT value.

**Comment by vruusmann** [comment]
Fundamentally, it's an XGBoost issue - empty decision trees should be "truncated" at the XGBoost library level (and never be stored into the XGBoost binary model file, and reach the JPMML-XGBoost library level).

@kelierlawu You can probably suppress empty decision trees by adjusting the `ntrees` option. Right now you're asking XGBoost to give you 500 decision trees, but XGBoost doesn't see any need for that many decision trees, so it "fills" the tail space with empty decision trees to make you happy.
