### ISSUE TITLE
AttributeError: 'Timestamp' object has no attribute '_get_object_id'

### ISSUE THREAD

**Issue by MC55652** [jpmml/jpmml-xgboost#52]
Hi,

I'm trying to run the pmml file I created, using pypmml package.
when running it on date features I get this error

     command_part = REFERENCE_TYPE + parameter._get_object_id()
     AttributeError: 'Timestamp' object has no attribute '_get_object_id'

I attached the pmml file as well.

Thanks.
[pmml_model_xgb_dates.zip](https://github.com/jpmml/jpmml-xgboost/files/5406511/pmml_model_xgb_dates.zip)

**Comment by vruusmann** [comment]
> I'm trying to run the pmml file I created, using pypmml package.

Please move this issue to the PyPMML project - it's not related to the JPMML-XGBoost project in any way.

**Comment by vruusmann** [comment]
> I'm trying to run the pmml file I created, using pypmml package.

In the Python environment, you should run PMML files using the [JPMML-Evaluator-Python](https://github.com/jpmml/jpmml-evaluator-python) package instead.

The JPMML-XGBoost library has been tested and found to be 100% compatible with JPMML-Evaluator(-Python). Use anything else at your own risk/expense.

**Comment by MC55652** [comment]
I tried using JPMML -Evaluator instead, as you suggested, but I still get the same error regarding date features:

    command_part = REFERENCE_TYPE + parameter._get_object_id()
    AttributeError: 'Timestamp' object has no attribute '_get_object_id'

What could cause this?

**Comment by vruusmann** [comment]
> I tried using JPMML -Evaluator instead, as you suggested, but I still get the same error regarding date features

This is definitely not a JPMML-Evaluator(-Python) error.

**Comment by vruusmann** [comment]
> I tried using JPMML -Evaluator instead, as you suggested, but I still get the same error regarding date features:

There is no `REFERENCE_TYPE + parameter._get_object_id()` code fragment anywhere in the JPMML software project (https://github.com/jpmml).

Prove me wrong with your error's stack trace.
