### ISSUE TITLE
question: xgboost required to evaluate model?

### ISSUE THREAD

**Issue by geoHeil** [jpmml/jpmml-xgboost#7]
I found this question on SF: http://stackoverflow.com/questions/37247783/xgboost4j-synchronization-issue and wonder if xgboost is still required to evaluate the model or if the problem mentioned there about synchronized calls to xgboost JNDI would be solved by converting the model to PMML.

**Comment by vruusmann** [comment]
If you convert an XGBoost model (or any other R, Scikit-Learn, etc model) to PMML representation, then it becomes fully decoupled from the original "runtime".

You execute PMML models using some PMML scoring engine, which may or may not have its own dependencies. For example, if you want to execute PMML models on JVM platform then you can use the [JPMML-Evaluator](https://github.com/jpmml/jpmml-evaluator) library for that. JPMML-Evaluator is implemented in pure Java, and works across on every JVM implementation, starting from Android and ending with Apache Spark/Apache Hadoop.

**Comment by vruusmann** [comment]
On a side note, XGBoost models are perfectly representable in PMML, including the handling of missing values, and default branches. The JPMML-XGBoost library is able to recognize and convert all built-in objective functions (binary and multi-class classification, linear and logistic regression, poisson regression).

It is also possible to do custom objective functions, if you implement an appropriate `org.jpmml.xgboost.ObjectiveFunction` subclass, and register it with the library.

**Comment by wynag01** [comment]
Hi @vruusmann, I've generated the xgboost pmml file according to the example you provided here: https://github.com/jpmml/r2pmml

But I am having issues using the model-evaluator (https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/regression/RegressionModelEvaluator.java) where it throws an exception cause the _target field is CONTINUOUS

org.jpmml.evaluator.InvalidFeatureException: DataField
	at org.jpmml.evaluator.regression.RegressionModelEvaluator.evaluateClassification(RegressionModelEvaluator.java:140)
	at org.jpmml.evaluator.regression.RegressionModelEvaluator.evaluate(RegressionModelEvaluator.java:89)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateSegmentation(MiningModelEvaluator.java:407)

Am I using the right model-evaluator? Any ideas on what is wrong here?

**Comment by vruusmann** [comment]
@wynag01 Indeed, looks like there's a problem with R2PMML integration, because the default target field for classification-type models is defined as "continuous double", not as "categorical double - one of 0, 1 or 2" as it should be:
```
<DataField name="_target" optype="categorical" dataType="double">
  <Value value="0"/>
  <Value value="1"/>
  <Value value="2"/>
</DataField>
```

For testing purposes, you can perform this correction manually. The rest of the PMML document is correct.

I will diagnose and fix this issue as soon as possible.

**Comment by wynag01** [comment]
Thanks @vruusmann, this line worked sufficiently for me:

`<DataField name="_target" optype="categorical" dataType="double">`

**Comment by vruusmann** [comment]
@wynag01 I've released an updated [r2pmml](https://github.com/jpmml/r2pmml) package (version 0.11.1) that includes this fix, and some other improvements. For example, it's also possible to customize the name and category levels of the target field:
```R
r2pmml(iris.xgb, fmap = iris.fmap, response_name = "Species", response_levels = c("setosa", "versicolor", "virginica"), "iris_xgb.pmml")
```

**Comment by wynag01** [comment]
Thanks @vruusmann! Just what I need 👍
