### ISSUE TITLE
different output of R and PMML

### ISSUE THREAD

**Issue by cnglen** [jpmml/jpmml-xgboost#9]
In R, the missing value is set to -1; 
It seems that PMML doesn't include this information. 

If the row of X contains a feature having value: "-1", the output of R is different from PMML's result.  Any ideas?

```
trainedModel <- xgboost(data = as.matrix(X), label = y, missing = -1,
                            eta = 0.1,
                            nround = 831,
                            max.depth = 5,
                            min_child_weight = 2,
                            gamma = 0.9,
                            subsample = 0.8,
                            lambda =  1.6,
                            alpha = 0.8,
                            nthread = 12,
                            objective = "binary:logistic",
                            verbose = 0)
```

**Comment by vruusmann** [comment]
You are correct that the JPMML-XGBoost library (which is invoked when you initiate the conversion using the `r2pmml` function in R) does not handle "custom" missing value specifications.

In the current case, you would want to append the following missing value specification to all `DataField` elements in the `DataDictionary` element:
```
<DataField name="someField" optype=".." dataType="..">
  <Value property="missing" value="-1"/>
</DataField>
```

You should be able to implement such post-processing step for R2PMML generated PMML documents in less than one hour using the [JPMML-Model](https://github.com/jpmml/jpmml-model) library. I will also try to implement it myself as soon as possible.

However, there's this technicality that how is the "literal value" of the missing value specification transferred over from the `xgboost(.., missing = -1, )` R function call to the actual trained XGBoost booster object. Could be the case that the JPMML-R library also needs some tweaking to make the solution work.

**Comment by vruusmann** [comment]
I've released [r2pmml](https://github.com/jpmml/r2pmml) version 0.11.1, where the `r2pmml.xgb.Booster` function now supports the `missing` argument (and also `response_name` and `response_levels` arguments):
```R
r2pmml(iris.xgb, fmap = iris.fmap, missing = -999, response_name = "Species", response_levels = c("setosa", "versicolor", "virginica"), "iris_xgb.pmml")
```
